# Exploratory Data Analysis

In [3]:
# import numpy
import numpy as np

In [16]:
arr1d = np.array([1,2,3,4])
print(f'Array 1 Dimensi : {arr1d}')
print(f'Ukuran array    : {arr1d.shape}')
print(f'Tipe data array : {arr1d.dtype}')

Array 1 Dimensi : [1 2 3 4]
Ukuran array    : (4,)
Tipe data array : int64


In [29]:
arr2d = np.array([
            [1,2,3],
            [4,5,6]
        ])
print(f'Array 2 Dimensi : \n{arr2d}')
print(f'Ukuran array    : {arr2d.shape}')
print(f'Tipe data array : {arr2d.dtype}')

Array 2 Dimensi : 
[[1 2 3]
 [4 5 6]]
Ukuran array    : (2, 3)
Tipe data array : int64


In [40]:
arr0 = np.zeros((4, 3))

print(f'Array 0         : \n{arr0}')

Array 0         : 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [41]:
arr1 = np.ones((4, 3))

print(f'Array 1         : \n{arr1}')

Array 1         : 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [42]:
# Matrix Identity
arrEye = np.eye(4)

print(f'Array Eye       : \n{arrEye}')

Array Eye       : 
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [43]:
# Matrix Range
arrRange = np.arange(0, 10, 4)

print(f'Array range     : \n{arrRange}')

Array range     : 
[0 4 8]


In [44]:
# Matrix Range
arrRange = np.arange(0, 10, 4)

print(f'Array range     : \n{arrRange}')

Array range     : 
[0 4 8]


In [54]:
# Matrix Linspace
arrRange = np.linspace(0, 10, 6)

print(f'Array linspace  : \n{arrRange}')

Array linspace  : 
[ 0.  2.  4.  6.  8. 10.]


In [61]:
# Array operation
arr1 = np.array([2, 4, 6, 8, 10])
arr2 = np.array([1, 2, 4, 4, 2])

print(f'Penjumlahan Array  : {arr1 + arr2}')
print(f'Pengurangan Array  : {arr1 + arr2}')
print(f'Perkalian Array    : {arr1 * arr2}')
print(f'Pembagian Array    : {arr1 / arr2}')

print(f'Perpangkatan Array : {arr1 ** arr2}')
print(f'Modulus Array      : {arr1 % arr2}')

Penjumlahan Array  : [ 3  6 10 12 12]
Pengurangan Array  : [ 3  6 10 12 12]
Perkalian Array    : [ 2  8 24 32 20]
Pembagian Array    : [2.  2.  1.5 2.  5. ]
Perpangkatan Array : [   2   16 1296 4096  100]
Modulus Array      : [0 0 2 0 0]


In [66]:
# Mathematical function

arr1 = np.array([1, 4, 9, 16, 25])
print(f'Akar kuadrat : {np.sqrt(arr1)}')
print(f'Eksponensial : {np.exp(arr1)}')

Akar kuadrat : [1. 2. 3. 4. 5.]
Eksponensial : [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10]


In [81]:
# Matrix Operation
m1 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

m2 = np.array([
    [10, 11, 12],
    [13, 14, 15],
    [16, 17, 18]
])

print(f'Penjumlahan Array  : \n{m1 + m2}')
print(f'Pengurangan Array  : \n{m1 + m2}')
print(f'Perkalian Array    : \n{np.dot(m1, m2)} \n\n{m1 @ m2}\n')
print(f'Transpose          : \n{m1.T} \n\n {m2.T}\n')
print(f'Inverse            : \n{np.linalg.inv(m1)}\n')
print(f'Determinan         : \n{np.linalg.det(m1)}\n')

Penjumlahan Array  : 
[[11 13 15]
 [17 19 21]
 [23 25 27]]
Pengurangan Array  : 
[[11 13 15]
 [17 19 21]
 [23 25 27]]
Perkalian Array    : 
[[ 84  90  96]
 [201 216 231]
 [318 342 366]] 

[[ 84  90  96]
 [201 216 231]
 [318 342 366]]

Transpose          : 
[[1 4 7]
 [2 5 8]
 [3 6 9]] 

 [[10 13 16]
 [11 14 17]
 [12 15 18]]

Inverse            : 
[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]

Determinan         : 
-9.51619735392994e-16



In [94]:
# Indexing dan Slicing
arr1 = [1, 2, 3, 4, 5, 6]
print(f'First Element  : {arr1[0]}')
print(f'Last  Element  : {arr1[-1]}')
print(f'Index [0-n]    : {arr1[:-1]}')
print(f'Index [n-last] : {arr1[4:]}')
print(f'Slice [m:n]    : {arr1[1:5]}')
print(f'Every 2nd      : {arr1[::2]}')
print(f'Reverse 2nd    : {arr1[::-2]}')

First Element  : 1
Last  Element  : 6
Index [0-n]    : [1, 2, 3, 4, 5]
Index [n-last] : [5, 6]
Slice [m:n]    : [2, 3, 4, 5]
Every 2nd      : [1, 3, 5]
Reverse 2nd    : [6, 4, 2]


# Pandas

In [104]:
import pandas as pd

# Load data
dataset = pd.read_csv('../Dataset/informatic_students.csv')
print(f'Shape  : {dataset.shape}')
print(f'Column : {dataset.columns.tolist()}')
print(f'Type   : \n{dataset.dtypes}\n')
print(dataset)

Shape  : (50, 5)
Column : ['Name', 'Age', 'GPA', 'Passed', 'Gender']
Type   : 
Name          str
Age         int64
GPA       float64
Passed       bool
Gender        str
dtype: object

           Name  Age   GPA  Passed  Gender
0        Robert   21  3.80    True    Male
1       Stefany   22  3.96    True  Female
2          Carl   20  3.00    True  Female
3         Louis   19  2.75   False  Female
4       William   22  2.75    True    Male
5        Karina   21  3.50    True  Female
6       Naelson   21  2.50   False    Male
7       Nicolas   18  2.10   False    Male
8        Olivia   20  3.45    True  Female
9        Marcus   22  2.90    True    Male
10      Jessica   19  3.75    True  Female
11        David   21  2.55   False    Male
12       Sophia   20  3.60    True  Female
13     Anderson   22  3.25    True    Male
14        Lucas   20  2.85   False    Male
15         Emma   21  3.90    True  Female
16     Benjamin   19  3.15    True    Male
17    Charlotte   22  3.55    True  Female

In [105]:
# Head 
print(f'Data Pertama  : {dataset.head(10)}')

Data Pertama  :       Name  Age   GPA  Passed  Gender
0   Robert   21  3.80    True    Male
1  Stefany   22  3.96    True  Female
2     Carl   20  3.00    True  Female
3    Louis   19  2.75   False  Female
4  William   22  2.75    True    Male
5   Karina   21  3.50    True  Female
6  Naelson   21  2.50   False    Male
7  Nicolas   18  2.10   False    Male
8   Olivia   20  3.45    True  Female
9   Marcus   22  2.90    True    Male


In [106]:
# Tail 
print(f'Data Pertama  : {dataset.tail(10)}')

Data Pertama  :         Name  Age   GPA  Passed  Gender
40    Joshua   22  2.95    True    Male
41     Grace   21  3.70    True  Female
42     Kevin   20  2.75   False    Male
43   Natalie   23  3.90    True  Female
44     Brian   21  3.25    True    Male
45      Lily   22  2.85   False  Female
46    Edward   19  3.60    True    Male
47  Scarlett   20  3.40    True  Female
48    Ronald   21  2.70   False    Male
49  Penelope   22  3.75    True  Female


In [112]:
# Basic Statistic
print(f'Describe : \n{dataset.describe()}')

Describe : 
             Age        GPA
count  50.000000  50.000000
mean   20.720000   3.234200
std     1.212856   0.477378
min    18.000000   2.100000
25%    20.000000   2.812500
50%    21.000000   3.250000
75%    22.000000   3.637500
max    23.000000   3.960000


In [118]:
# New Column
dataset['Letter'] = dataset['GPA'].apply(lambda x: 'Cumlaude' if x >= 3.50 else 'Selamat' if x >= 3.00 else 'Semangat')
print(dataset)

           Name  Age   GPA  Passed  Gender    Letter
0        Robert   21  3.80    True    Male  Cumlaude
1       Stefany   22  3.96    True  Female  Cumlaude
2          Carl   20  3.00    True  Female   Selamat
3         Louis   19  2.75   False  Female  Semangat
4       William   22  2.75    True    Male  Semangat
5        Karina   21  3.50    True  Female  Cumlaude
6       Naelson   21  2.50   False    Male  Semangat
7       Nicolas   18  2.10   False    Male  Semangat
8        Olivia   20  3.45    True  Female   Selamat
9        Marcus   22  2.90    True    Male  Semangat
10      Jessica   19  3.75    True  Female  Cumlaude
11        David   21  2.55   False    Male  Semangat
12       Sophia   20  3.60    True  Female  Cumlaude
13     Anderson   22  3.25    True    Male   Selamat
14        Lucas   20  2.85   False    Male  Semangat
15         Emma   21  3.90    True  Female  Cumlaude
16     Benjamin   19  3.15    True    Male   Selamat
17    Charlotte   22  3.55    True  Female  Cu

In [122]:
dataset_drop = dataset.drop('Letter', axis = 1)
print(dataset_drop)

           Name  Age   GPA  Passed  Gender
0        Robert   21  3.80    True    Male
1       Stefany   22  3.96    True  Female
2          Carl   20  3.00    True  Female
3         Louis   19  2.75   False  Female
4       William   22  2.75    True    Male
5        Karina   21  3.50    True  Female
6       Naelson   21  2.50   False    Male
7       Nicolas   18  2.10   False    Male
8        Olivia   20  3.45    True  Female
9        Marcus   22  2.90    True    Male
10      Jessica   19  3.75    True  Female
11        David   21  2.55   False    Male
12       Sophia   20  3.60    True  Female
13     Anderson   22  3.25    True    Male
14        Lucas   20  2.85   False    Male
15         Emma   21  3.90    True  Female
16     Benjamin   19  3.15    True    Male
17    Charlotte   22  3.55    True  Female
18    Alexander   21  2.65   False    Male
19       Amelia   20  3.70    True  Female
20       Daniel   23  2.95    True    Male
21          Mia   19  3.40    True  Female
22      Mic